#!/bin/bash -e

# Make sure we're in the right place
cd "${APPRUN_ROOT}"

chown -R www-data:www-data /app/*

# Run the actual app here
	exec 2>&1 \
	  chpst -u www-data \
	     pipenv run /app/bin/steemyo 2>&1
