from aiohttp import web

def gen_static_handler(content='',content_type='text/html'):
    """ Returns a function that can be used as an aiohttp handler

    This is intended for use with static content loaded at startup

    Keyword Args:
       content(str):      the raw content
       content_type(str): the content type as will be set in the response header
    """
    async def internal_handler(request):
          return web.Response(body=content,content_type=content_type)
    return internal_handler

def loadfile(filename):
    """ Utility function that just grabs the contents of a file from disk
    """
    fd = open(filename,'r')
    retval = fd.read()
    fd.close()
    return retval

def gen_static_fromfile(filename='static/index.html',template_replace={},content_type='text/html'):
    """ Returns a function generated by gen_static_handler() with content loaded from the specified file

    Keyword Args:
       filename(str):          the file to load from
       template_replace(dict): maps strings to replace in the file with their replacements
       content_type(str):      content type to set in response header

    """
    file_content = loadfile(filename)
    for k,v in template_replace.items():
        file_content = file_content.replace(k,v)
    return gen_static_handler(content=file_content,content_type=content_type)

def add_static_files(app,files={},template_replace={}):
    """ Adds a bunch of static files to a web app, taking care of template substitution and routes

    Args:
       app: the aiohttp.web app

    Keyword args:
       files(dict):             maps paths to tuples consisting of (filename,content_type)
       template_replace(dict):  maps strings to replace in each file
    """
    for k,v in files.items():
        app.router.add_get(k,gen_static_fromfile(filename=v[0],template_replace=template_replace,content_type=v[1]))

def add_wwwpush_statics(app):
    """ Adds the required static content for browser push notifications

    Args:
        app: the app to work with
    """
    add_static_files(app,files={'/pushdemo':                     ('./html/wwwpush_demo.html',      'text/html'),
                                '/pushdemo/manifest.json':       ('./json/wwwpush_manifest.json',  'text/json'),
                                '/pushdemo/js/service-worker.js':('./js/wwwpush_service_worker.js','text/javascript'),
                                '/pushdemo/js/wwwpush.js':       ('./js/wwwpush.js',               'text/javascript')},
                         template_replace={'%%SERVER_KEY%%':loadfile('./wwwpush_pubkey.txt')})
